name: 'Pull Request Previews'

on:
  workflow_run:
    workflows: [PR Commit]
    types:
      - completed
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: matyrobbrt/cloudflare-pr-previews@main
        with:
          gh_app_key: ${{ secrets.GH_APP_KEY }}
          gh_app_name: ${{ secrets.GH_APP_NAME }}
          project_name: 'neoforged-docs-previews'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
